=== qcadoo/mes/mes-model/src/main/resources/com/qcadoo/model/model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/model" xmlns="http://www.qcadoo.com/model" elementFormDefault="qualified">

	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="integer" type="fieldType" />
					<xs:element name="string" type="stringFieldType" />
					<xs:element name="text" type="fieldType" />
					<xs:element name="decimal" type="fieldType" />
					<xs:element name="datetime" type="fieldType" />
					<xs:element name="date" type="fieldType" />
					<xs:element name="boolean" type="fieldType" />
					<xs:element name="belongsTo" type="belongsToFieldType" />
					<xs:element name="hasMany" type="hasManyFieldType" />
					<xs:element name="tree" type="treeFieldType" />
					<xs:element name="enum" type="enumFieldType" />
					<xs:element name="dictionary" type="dictionaryFieldType" />
					<xs:element name="password" type="fieldType" />
				</xs:choice>
				<xs:element name="priority" type="priorityFieldType"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="validatesWith" type="hookType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="onSave" type="hookType" />
					<xs:element name="onUpdate" type="hookType" />
					<xs:element name="onCreate" type="hookType" />
					<xs:element name="onCopy" type="hookType" />
					<xs:element name="onView" type="hookType" />
				</xs:choice>
				<xs:element name="identifier" type="identifierExpressionType"
					minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" type="identifierType" use="required" />
			<xs:attribute name="plugin" type="identifierType" use="optional" />
			<xs:attribute name="deletable" type="xs:boolean" />
			<xs:attribute name="insertable" type="xs:boolean" />
			<xs:attribute name="updatable" type="xs:boolean" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="identifierExpressionType">
		<xs:attribute name="expression" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="validatesType">
		<xs:attribute name="message" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="validatesLengthType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="min" type="xs:integer" />
				<xs:attribute name="is" type="xs:integer" />
				<xs:attribute name="max" type="xs:integer" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="validatesRangeType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="from" type="xs:string" />
				<xs:attribute name="to" type="xs:string" />
				<xs:attribute name="exclusively" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="validatesRegexType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="pattern" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="hookType">
		<xs:attribute name="class" type="classType" use="required" />
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="validatesWith" type="hookType" />
			<xs:element name="validatesLength" type="validatesLengthType" />
			<xs:element name="validatesPrecision" type="validatesLengthType" />
			<xs:element name="validatesScale" type="validatesLengthType" />
			<xs:element name="validatesRange" type="validatesRangeType" />
			<xs:element name="validatesRegex" type="validatesRegexType" />
		</xs:choice>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="default" type="xs:string" />
		<xs:attribute name="readonly" type="xs:boolean" default="false" />
		<xs:attribute name="persistent" type="xs:boolean" default="true" />
		<xs:attribute name="required" type="xs:boolean" default="false" />
		<xs:attribute name="unique" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="stringFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="expression" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="belongsToFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="lazy" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hasManyFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="none" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="treeFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="none" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="dictionaryFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="plugin" type="identifierType" use="optional" />
				<xs:attribute name="dictionary" type="identifierType"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="enumFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="values" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9]*(,[a-zA-Z0-9]*)*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="priorityFieldType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="scope" type="identifierType" use="optional" />
	</xs:complexType>

	<xs:simpleType name="cascadeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="delete" />
			<xs:enumeration value="none" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="deletableType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="false" />
			<xs:enumeration value="true" />
			<xs:enumeration value="soft" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9.]*.[a-zA-Z0-9]+" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== qcadoo/mes/mes-plugins/mes-plugins-material-flow-resources/src/main/resources/materialFlowResources/model/resourceCorrection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="resourceCorrection"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd" auditable="true">
    <fields>
        <string name="number"/>
        <belongsTo name="product" model="product" plugin="basic"/>
        <decimal name="newQuantity">
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="oldQuantity">
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <belongsTo name="location" model="location" plugin="materialFlow"/>
        <datetime name="time"/>

        <string name="_oldBatch"/>
        <string name="_newBatch"/>

        <belongsTo name="oldBatch" model="batch" plugin="advancedGenealogy"/>
        <belongsTo name="newBatch" model="batch" plugin="advancedGenealogy"/>

        <belongsTo name="resource" model="resource"/>

        <belongsTo name="oldStorageLocation" model="storageLocation"/>
        <belongsTo name="newStorageLocation" model="storageLocation"/>

        <decimal name="oldPrice"/>
        <decimal name="newPrice"/>

        <decimal name="oldConversion"/>
        <decimal name="newConversion"/>

        <belongsTo name="oldPalletNumber" model="palletNumber" plugin="basic"/>
        <belongsTo name="newPalletNumber" model="palletNumber" plugin="basic"/>

        <belongsTo name="oldTypeOfLoadUnit" plugin="basic" model="typeOfLoadUnit" />
        <belongsTo name="newTypeOfLoadUnit" plugin="basic" model="typeOfLoadUnit" />

        <date name="oldExpirationDate"/>
        <date name="newExpirationDate"/>

        <date name="productionDate"/>
        <string name="resourceNumber"/>
        <string name="deliveryNumber"/>

        <dictionary name="oldQualityRating" dictionary="qualityRating"/>
        <dictionary name="newQualityRating" dictionary="qualityRating"/>

        <hasMany name="resourceAttributeValueAfterCorrections" joinField="resourceCorrection"
                       model="resourceAttributeValueAfterCorrection" cascade="nullify"/>

        <hasMany name="resourceAttributeValueBeforeCorrections" joinField="resourceCorrection"
                       model="resourceAttributeValueBeforeCorrection" cascade="nullify"/>

    </fields>
    <hooks/>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-technologies/src/main/resources/technologies/model/modifyTechnologyHelper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="modifyTechnologyHelper" auditable="true"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <boolean name="remove" default="false"/>
        <boolean name="addNew" default="false"/>
        <boolean name="replace" default="false"/>
        <string name="selectedEntities" required="true"/>
        <belongsTo name="product" plugin="basic" model="product"
                   required="true"/>
        <belongsTo name="replaceProduct" plugin="basic" model="product"/>
        <decimal name="replaceProductQuantity">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>

        <hasMany name="modifyTechnologyAddProducts" model="modifyTechnologyAddProductHelper"
                 joinField="modifyTechnologyHelper" cascade="delete"/>

    </fields>
    <hooks>
        <validatesWith
                class="com.qcadoo.mes.technologies.validators.ModifyTechnologyHelperValidators"
                method="validatesWith"/>
    </hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-production-counting/src/main/resources/productionCounting/model/recordOperationProductInComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.2.0

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="recordOperationProductInComponent" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<belongsTo name="productionRecord" model="productionRecord" />
		<belongsTo name="product" model="product" plugin="basic" />
		<decimal name="plannedQuantity" persistent="false" />
		<decimal name="usedQuantity">
			<validatesRange from="0" exclusively="false" />
		</decimal>
		<decimal name="balance" />
	</fields>
	<hooks>
		<onView
			class="com.qcadoo.mes.productionCounting.hooks.RecordOperationProductInComponentHooks"
			method="fillPlannedQuantity" />
	</hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-basic/src/main/resources/basic/model/division.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.3

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="division" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <string name="number" required="true" unique="true">
            <validatesLength max="255"/>
        </string>
        <string name="name" required="true">
            <validatesLength max="1024"/>
        </string>
        <belongsTo name="supervisor" model="staff"/>
        <belongsTo name="factory" model="factory"/>
        <!-- <manyToMany name="workstationTypes" model="workstationType"
            joinField="divisions" /> -->
        <hasMany name="workstations" model="workstation" joinField="division" cascade="nullify"/>
    </fields>

    <hooks/>

    <identifier expression="#number + ' - ' + #name"/>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-master-orders/src/main/resources/masterOrders/model/salesPlanStateChange.xml
<model name="salesPlanStateChange"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

    <fields>
        <!-- generic state change fields -->
        <datetime name="dateAndTime"/>
        <enum name="sourceState"
              values="01draft,02rejected,03completed"/>
        <enum name="targetState"
              values="01draft,02rejected,03completed"
              required="true"/>
        <enum name="status"
              values="01inProgress,02paused,03successful,04failure,05canceled"
              required="true"/>
        <integer name="phase"/>
        <string name="worker"/>
        <belongsTo name="salesPlan" model="salesPlan"/>
        <belongsTo name="shift" model="shift" plugin="basic"/>
    </fields>

    <hooks/>

</model>

=== qcadoo/mes/mes-plugins/mes-plugins-material-flow-resources/src/main/resources/materialFlowResources/model/position.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="position"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <belongsTo name="document" model="document"/>
        <belongsTo name="product" model="product" plugin="basic"
                   required="true"/>
        <decimal name="quantity" required="true">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="givenQuantity">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="price" default="0">
            <validatesRange from="0"/>
        </decimal>
        <decimal name="sellingPrice" default="0">
            <validatesRange from="0"/>
        </decimal>
        <belongsTo name="batch" model="batch" plugin="advancedGenealogy"/>

        <string name="unit" persistent="false"/>
        <dictionary name="givenUnit" dictionary="units"/>

        <date name="productionDate"/>
        <date name="expirationDate"/>
        <priority name="number" scope="document"/>
        <belongsTo name="resource" model="resource"/>
        <string name="resourceNumber"/>
        <string name="transferResourceNumber"/>

        <belongsTo name="storageLocation" model="storageLocation"/>

        <decimal name="conversion" default="0"/>
        <belongsTo name="palletNumber" model="palletNumber" plugin="basic"/>
        <dictionary name="typeOfPallet" dictionary="typeOfPallet"/>

        <hasMany name="reservations" model="reservation" joinField="position" copyable="true" cascade="delete"/>

        <string name="resourceReceiptDocument"/>

        <boolean name="waste" default="false"/>
        <dictionary name="qualityRating" dictionary="qualityRating"/>
        <datetime name="pickingDate" copyable="false"/>
        <belongsTo name="pickingWorker" model="user" plugin="qcadooSecurity" copyable="false"/>
        <hasMany name="positionAttributeValues" joinField="position"
                       model="positionAttributeValue"/>
    </fields>
    <hooks>
        <onCreate class="com.qcadoo.mes.materialFlowResources.hooks.PositionModelHooks" method="onCreate"/>
        <onCopy class="com.qcadoo.mes.materialFlowResources.hooks.PositionModelHooks" method="onCopy"/>
        <onSave class="com.qcadoo.mes.materialFlowResources.hooks.PositionModelHooks" method="onSave"/>
        <onDelete class="com.qcadoo.mes.materialFlowResources.hooks.PositionModelHooks" method="onDelete"/>
        <validatesWith class="com.qcadoo.mes.materialFlowResources.validators.PositionValidators"
                       method="checkAttributesRequirement"/>
        <validatesWith class="com.qcadoo.mes.materialFlowResources.validators.PositionValidators"
                       method="validateDates"/>

    </hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-order-supplies/src/main/resources/orderSupplies/model/materialRequirementCoverage.xml
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo Framework
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="materialRequirementCoverage" auditable="true" cacheable="true"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

    <fields>
        <string name="number" required="true" unique="true">
            <validatesLength max="255"/>
        </string>

        <datetime name="coverageToDate" required="true"/>
        <datetime name="actualDate" required="true"/>
        <datetime name="generatedDate"/>
        <string name="generatedBy">
            <validatesLength max="255"/>
        </string>
        <boolean name="orderGenerationInProgress" default="false"/>
        <boolean name="generated"/>
        <boolean name="saved"/>
        <boolean name="automaticSaveCoverage" default="false"/>
        <string name="fileName">
            <validatesLength max="1024"/>
        </string>

        <enum name="coverageType"
              values="01all,02withoutProductsFromWarehouse,03onlyShorcomingsAndDelays" default="01all" required="true"/>

        <enum name="includeInCalculationDeliveries"
                    values="01confirmedDeliveries,02unconfirmedDeliveries,03nonDraftDeliveries"
                    required="true" default="01confirmedDeliveries"/>
        <hasMany name="coverageLocations" joinField="materialRequirementCoverage"
                 model="coverageLocation" cascade="delete" copyable="true"/>

        <hasMany name="coverageAnalysisForOrders" joinField="materialRequirementCoverage"
                 model="coverageAnalysisForOrder" cascade="delete" copyable="true"/>
        <hasMany name="coverageAnalysisForOrdersDto" joinField="materialRequirementCoverage"
                 model="coverageAnalysisForOrderDto" cascade="delete" copyable="true" persistent="false"/>

        <hasMany name="coverageProducts" joinField="materialRequirementCoverage"
                 model="coverageProduct" cascade="delete" copyable="true"/>
        <hasMany name="coverageProductsDto" joinField="materialRequirementCoverage" model="coverageProductDto"
                 persistent="false"/>

        <manyToMany name="coverageOrders" joinField="materialRequirementCoverages" model="order"
                    plugin="orders"/>

        <hasMany name="coverageOrderStates" model="coverageOrderState" plugin="orderSupplies"
                 joinField="materialRequirementCoverage" cascade="delete" copyable="true"/>
    </fields>

    <hooks>
        <validatesWith
                class="com.qcadoo.mes.orderSupplies.validators.MaterialRequirementCoverageValidators"
                method="validatesWith"/>
    </hooks>

    <identifier expression="#number"/>

</model>

=== qcadoo/mes/mes-plugins/mes-plugins-material-flow-resources/src/main/resources/materialFlowResources/model/documentPositionParametersItem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="documentPositionParametersItem"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <string name="name" required="true" unique="true" />
        <string name="displayName" persistent="false" readonly="true" />
        <boolean name="checked" default="true" />
        <boolean name="editable" default="true" />
        <priority name="ordering" />
        
        <belongsTo name="parameters" model="documentPositionParameters"/>

        <boolean name="forAttribute" default="false" />
        <belongsTo name="attribute" model="attribute" plugin="basic"/>
    </fields>
    <hooks/>
</model>
