=== qcadoo/mes/mes-model/src/main/resources/com/qcadoo/model/model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/model" xmlns="http://www.qcadoo.com/model" elementFormDefault="qualified">

	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="integer" type="fieldType" />
					<xs:element name="string" type="stringFieldType" />
					<xs:element name="text" type="fieldType" />
					<xs:element name="decimal" type="fieldType" />
					<xs:element name="datetime" type="fieldType" />
					<xs:element name="date" type="fieldType" />
					<xs:element name="boolean" type="fieldType" />
					<xs:element name="belongsTo" type="belongsToFieldType" />
					<xs:element name="hasMany" type="hasManyFieldType" />
					<xs:element name="tree" type="treeFieldType" />
					<xs:element name="enum" type="enumFieldType" />
					<xs:element name="dictionary" type="dictionaryFieldType" />
					<xs:element name="password" type="fieldType" />
				</xs:choice>
				<xs:element name="priority" type="priorityFieldType"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="validatesWith" type="hookType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="onSave" type="hookType" />
					<xs:element name="onUpdate" type="hookType" />
					<xs:element name="onCreate" type="hookType" />
					<xs:element name="onCopy" type="hookType" />
					<xs:element name="onView" type="hookType" />
				</xs:choice>
				<xs:element name="identifier" type="identifierExpressionType"
					minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" type="identifierType" use="required" />
			<xs:attribute name="plugin" type="identifierType" use="optional" />
			<xs:attribute name="deletable" type="xs:boolean" />
			<xs:attribute name="insertable" type="xs:boolean" />
			<xs:attribute name="updatable" type="xs:boolean" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="identifierExpressionType">
		<xs:attribute name="expression" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="validatesType">
		<xs:attribute name="message" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="validatesLengthType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="min" type="xs:integer" />
				<xs:attribute name="is" type="xs:integer" />
				<xs:attribute name="max" type="xs:integer" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="validatesRangeType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="from" type="xs:string" />
				<xs:attribute name="to" type="xs:string" />
				<xs:attribute name="exclusively" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="validatesRegexType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="pattern" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="hookType">
		<xs:attribute name="class" type="classType" use="required" />
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="validatesWith" type="hookType" />
			<xs:element name="validatesLength" type="validatesLengthType" />
			<xs:element name="validatesPrecision" type="validatesLengthType" />
			<xs:element name="validatesScale" type="validatesLengthType" />
			<xs:element name="validatesRange" type="validatesRangeType" />
			<xs:element name="validatesRegex" type="validatesRegexType" />
		</xs:choice>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="default" type="xs:string" />
		<xs:attribute name="readonly" type="xs:boolean" default="false" />
		<xs:attribute name="persistent" type="xs:boolean" default="true" />
		<xs:attribute name="required" type="xs:boolean" default="false" />
		<xs:attribute name="unique" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="stringFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="expression" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="belongsToFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="lazy" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hasManyFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="none" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="treeFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="none" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="dictionaryFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="plugin" type="identifierType" use="optional" />
				<xs:attribute name="dictionary" type="identifierType"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="enumFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="values" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9]*(,[a-zA-Z0-9]*)*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="priorityFieldType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="scope" type="identifierType" use="optional" />
	</xs:complexType>

	<xs:simpleType name="cascadeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="delete" />
			<xs:enumeration value="none" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="deletableType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="false" />
			<xs:enumeration value="true" />
			<xs:enumeration value="soft" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9.]*.[a-zA-Z0-9]+" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== qcadoo/mes/mes-plugins/mes-plugins-technologies/src/main/resources/technologies/model/operationProductInComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="operationProductInComponent"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

    <fields>
        <belongsTo name="technology" model="technology" persistent="false"/>
        <belongsTo name="operationComponent" model="technologyOperationComponent"
                   required="true"/>
        <priority name="priority" scope="operationComponent"/>
        <belongsTo name="product" plugin="basic" model="product"/>
        <decimal name="quantity">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="givenQuantity">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <dictionary name="givenUnit" dictionary="units"/>
        <string name="quantityFormula" />
        <belongsTo name="technologyInputProductType" model="technologyInputProductType"/>
        <boolean name="differentProductsInDifferentSizes" default="false"/>
        <boolean name="variousQuantitiesInProductsBySize" default="false"/>
        <hasMany name="productBySizeGroups" model="productBySizeGroup"
                 joinField="operationProductInComponent" cascade="delete" copyable="true"/>
        <string name="description">
            <validatesLength max="2048"/>
        </string>

        <belongsTo name="attribute" model="attribute" plugin="basic"/>

        <boolean name="showInProductData" default="false"/>
        <decimal name="productDataNumber" default="0"/>

        <hasMany name="productDataInputs" model="productDataInput" joinField="operationProductInComponent"
                 cascade="delete"/>

        <hasMany name="sections" model="section" joinField="operationProductInComponent" copyable="true"
                 cascade="delete"/>
    </fields>

    <hooks>
        <onSave class="com.qcadoo.mes.technologies.hooks.OperationProductInComponentHooks"
                       method="onSave"/>
        <validatesWith class="com.qcadoo.mes.technologies.hooks.OperationProductInComponentHooks"
                       method="validatesWith"/>
    </hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-material-flow-resources/src/main/resources/materialFlowResources/model/resourceDto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="resourceDto"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd"
       activable="false" auditable="false" deletable="false" insertable="false" updatable="false">

    <fields>
        <string name="number"/>
        <string name="locationNumber"/>
        <integer name="location_id"/>
        <string name="productNumber"/>
        <string name="productName"/>
        <enum name="productGlobalTypeOfMaterial" values="01component,02intermediate,03finalProduct,04waste,05package"/>
        <decimal name="quantity"/>
        <string name="productUnit"/>
        <dictionary name="productCategory" dictionary="categories"/>
        <decimal name="quantityInAdditionalUnit"/>
        <string name="givenUnit"/>
        <decimal name="conversion"/>
        <decimal name="reservedQuantity"/>
        <decimal name="availableQuantity"/>
        <decimal name="price"/>
        <decimal name="value"/>
        <datetime name="time"/>
        <date name="productionDate"/>
        <date name="expirationDate"/>
        <string name="batchNumber"/>
        <string name="storageLocationNumber"/>
        <string name="palletNumber"/>
        <string name="typeOfLoadUnit"/>
        <string name="qualityRating"/>
        <string name="userName"/>
        <boolean name="isCorrected"/>
        <boolean name="waste"/>
        <string name="deliveryNumber"/>
        <string name="supplierNumber"/>
        <string name="documentNumber"/>
        <belongsTo name="positionAddMultiHelper" model="positionAddMultiHelper"/>
        <boolean name="blockedForQualityControl"/>
        <decimal name="colorResourcesAfterDeadline"/>
        <string name="expirationDateCellColor"/>
    </fields>

    <masterModel plugin="materialFlowResources" model="resource"/>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-material-flow-resources/src/main/resources/materialFlowResources/model/resource.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="resource"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

    <fields>
        <!-- number generated in database trigger -->
        <string name="number" unique="true"/>
        <belongsTo name="location" model="location" plugin="materialFlow"
                   required="true"/>
        <belongsTo name="product" model="product" plugin="basic"
                   required="true"/>
        <decimal name="quantity" required="true">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="price" default="0"/>

        <decimal name="value" persistent="false"/>
        <string name="_batch"/>
        <belongsTo name="batch" model="batch" plugin="advancedGenealogy"/>
        <datetime name="time" required="true"/>
        <datetime name="createDate"/>
        <date name="productionDate"/>
        <date name="expirationDate"/>
        <hasMany name="positions" joinField="resource" model="position"/>
        <hasMany name="resourceCorrections" joinField="resource" model="resourceCorrection"/>
        <boolean name="isCorrected" default="false"/>

        <belongsTo name="storageLocation" model="storageLocation"/>

        <decimal name="quantityInAdditionalUnit">
            <validatesRange from="0" exclusively="true"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="conversion" default="0"/>
        <belongsTo name="palletNumber" model="palletNumber" plugin="basic"/>
        <belongsTo name="typeOfLoadUnit" plugin="basic" model="typeOfLoadUnit" />
        <dictionary name="givenUnit" dictionary="units"/>
        <string name="userName"/>
        <boolean name="waste" default="false"/>

        <hasMany name="reservations" model="reservation" joinField="resource" cascade="delete"/>

        <decimal name="reservedQuantity">
            <validatesRange from="0"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="availableQuantity">
            <validatesRange from="0"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>

        <boolean name="validatePallet" default="true" persistent="false"/>

        <string name="deliveryNumber"/>
        <string name="documentNumber"/>

        <dictionary name="qualityRating" dictionary="qualityRating"/>
        <boolean name="blockedForQualityControl" default="false"/>
        <hasMany name="resourceAttributeValues" joinField="resource"
                       model="resourceAttributeValue" cascade="delete"/>
        <hasMany name="repackingPositions" joinField="resource" model="repackingPosition"/>
        <string name="resourceIds" persistent="false"/>
    </fields>

    <hooks>        
        <validatesWith
                class="com.qcadoo.mes.materialFlowResources.hooks.ResourceModelValidators"
                method="validatesWith"/>
        <onCreate
                class="com.qcadoo.mes.materialFlowResources.hooks.ResourceModelHooks"
                method="onCreate"/>
        <onSave
                class="com.qcadoo.mes.materialFlowResources.hooks.ResourceModelHooks"
                method="onSave"/>
    </hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-basic/src/main/resources/basic/model/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- *************************************************************************** 
	Copyright (c) 2010 Qcadoo Limited Project: Qcadoo MES Version: 1.2.0-SNAPSHOT 
	This file is part of Qcadoo. Qcadoo is free software; you can redistribute 
	it and/or modify it under the terms of the GNU Affero General Public License 
	as published by the Free Software Foundation; either version 3 of the License, 
	or (at your option) any later version. This program is distributed in the 
	hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
	warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU Affero General Public License for more details. You should have received 
	a copy of the GNU Affero General Public License along with this program; 
	if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth 
	Floor, Boston, MA 02110-1301 USA 
*************************************************************************** -->
<model name="company" activable="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<string name="number" required="true" unique="true">
			<validatesLength max="255" />
		</string>
		<string name="name" required="true">
			<validatesLength max="255" />
		</string>
		<string name="tax" />
		<string name="street" />
		<string name="house">
			<validatesLength max="30" />
		</string>
		<string name="flat">
			<validatesLength max="30" />
		</string>
		<string name="zipCode">
			<validatesLength max="6" />
		</string>
		<string name="city" />
		<string name="state" />
		<string name="country" />
		<string name="email" />
		<string name="website" />
		<string name="phone" />
		<string name="externalNumber" unique="true"/>

	</fields>
	<hooks />
	<identifier expression="#number + ' - ' + #name" />
</model>
