=== qcadoo/mes/mes-model/src/main/resources/com/qcadoo/model/model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.qcadoo.com/model" xmlns="http://www.qcadoo.com/model" elementFormDefault="qualified">

	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="integer" type="fieldType" />
					<xs:element name="string" type="stringFieldType" />
					<xs:element name="text" type="fieldType" />
					<xs:element name="decimal" type="fieldType" />
					<xs:element name="datetime" type="fieldType" />
					<xs:element name="date" type="fieldType" />
					<xs:element name="boolean" type="fieldType" />
					<xs:element name="belongsTo" type="belongsToFieldType" />
					<xs:element name="hasMany" type="hasManyFieldType" />
					<xs:element name="tree" type="treeFieldType" />
					<xs:element name="enum" type="enumFieldType" />
					<xs:element name="dictionary" type="dictionaryFieldType" />
					<xs:element name="password" type="fieldType" />
				</xs:choice>
				<xs:element name="priority" type="priorityFieldType"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="validatesWith" type="hookType"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="onSave" type="hookType" />
					<xs:element name="onUpdate" type="hookType" />
					<xs:element name="onCreate" type="hookType" />
					<xs:element name="onCopy" type="hookType" />
					<xs:element name="onView" type="hookType" />
				</xs:choice>
				<xs:element name="identifier" type="identifierExpressionType"
					minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" type="identifierType" use="required" />
			<xs:attribute name="plugin" type="identifierType" use="optional" />
			<xs:attribute name="deletable" type="xs:boolean" />
			<xs:attribute name="insertable" type="xs:boolean" />
			<xs:attribute name="updatable" type="xs:boolean" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="identifierExpressionType">
		<xs:attribute name="expression" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="validatesType">
		<xs:attribute name="message" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="validatesLengthType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="min" type="xs:integer" />
				<xs:attribute name="is" type="xs:integer" />
				<xs:attribute name="max" type="xs:integer" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="validatesRangeType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="from" type="xs:string" />
				<xs:attribute name="to" type="xs:string" />
				<xs:attribute name="exclusively" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="validatesRegexType">
		<xs:complexContent>
			<xs:extension base="validatesType">
				<xs:attribute name="pattern" type="xs:string" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="hookType">
		<xs:attribute name="class" type="classType" use="required" />
		<xs:attribute name="method" type="identifierType" use="required" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="validatesWith" type="hookType" />
			<xs:element name="validatesLength" type="validatesLengthType" />
			<xs:element name="validatesPrecision" type="validatesLengthType" />
			<xs:element name="validatesScale" type="validatesLengthType" />
			<xs:element name="validatesRange" type="validatesRangeType" />
			<xs:element name="validatesRegex" type="validatesRegexType" />
		</xs:choice>
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="default" type="xs:string" />
		<xs:attribute name="readonly" type="xs:boolean" default="false" />
		<xs:attribute name="persistent" type="xs:boolean" default="true" />
		<xs:attribute name="required" type="xs:boolean" default="false" />
		<xs:attribute name="unique" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:complexType name="stringFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="expression" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="belongsToFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="lazy" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="hasManyFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="none" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="treeFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="model" type="identifierType" use="required" />
				<xs:attribute name="plugin" type="identifierType" />
				<xs:attribute name="joinField" type="identifierType"
					use="required" />
				<xs:attribute name="cascade" type="cascadeType" default="none" />
				<xs:attribute name="copyable" type="xs:boolean" default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="dictionaryFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="plugin" type="identifierType" use="optional" />
				<xs:attribute name="dictionary" type="identifierType"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="enumFieldType">
		<xs:complexContent>
			<xs:extension base="fieldType">
				<xs:attribute name="values" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9]*(,[a-zA-Z0-9]*)*" />
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="priorityFieldType">
		<xs:attribute name="name" type="identifierType" use="required" />
		<xs:attribute name="scope" type="identifierType" use="optional" />
	</xs:complexType>

	<xs:simpleType name="cascadeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="delete" />
			<xs:enumeration value="none" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="deletableType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="false" />
			<xs:enumeration value="true" />
			<xs:enumeration value="soft" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="identifierType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-z][a-zA-Z0-9.]*.[a-zA-Z0-9]+" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== qcadoo/mes/mes-plugins/mes-plugins-production-scheduling/src/main/resources/productionScheduling/model/orderOperationComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.1.2

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="orderOperationComponent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<belongsTo name="order" plugin="orders" model="order"
			required="true" />
		<belongsTo name="technology" plugin="technologies" model="technology"
			required="true" />
		<belongsTo name="operation" plugin="technologies" model="operation"
			required="true" />
		<belongsTo name="technologyOperationComponent" plugin="technologies"
			model="technologyOperationComponent" required="true" />
		<belongsTo name="parent" model="orderOperationComponent" />
		<enum name="entityType" values="operation" required="true"
			default="operation" />
		<hasMany name="children" model="orderOperationComponent"
			joinField="parent" cascade="delete" copyable="true" />
		<priority name="priority" scope="parent" />
		<integer name="tpz" default="0" required="true"/>
		<integer name="tj" default="0" required="true"/>
		<decimal name="productionInOneCycle" required="true" default="1" />
		<enum name="countRealized" values="01all,02specified" default="01all"
			required="true" />
		<decimal name="countMachine" default="0.0" required="true"/>
		<integer name="timeNextOperation" default="0" required="true"/>
		<decimal name="machineUtilization" required="true" default="1.0" >
			<validatesUnscaledValue max="3" />
			<validatesScale max="3" />
		</decimal>
		<decimal name="laborUtilization" required="true" default="1.0">
			<validatesUnscaledValue max="3" />
			<validatesScale max="3" />
		</decimal>
		<integer name="operationOffSet" />
		<integer name="effectiveOperationRealizationTime" />
		<datetime name="effectiveDateFrom" />
		<datetime name="effectiveDateTo" />
		
		<string name="nodeNumber" />
	</fields>
	<hooks />
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-technologies/src/main/resources/technologies/model/operation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="operation" activable="true"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

    <fields>
        <string name="number" required="true" unique="true">
            <validatesLength max="255"/>
        </string>
        <string name="name" required="true">
            <validatesLength max="1024"/>
        </string>
        <string name="comment">
            <validatesLength max="2048"/>
        </string>

        <file name="attachment"/>
        <boolean name="areProductQuantitiesDivisible" default="false"/>
        <boolean name="isTjDivisible" default="false"/>
        <boolean name="optimizeCutting" default="false"/>

        <belongsTo name="operationGroup" model="operationGroup"/>

        <hasMany name="operationComponents" model="technologyOperationComponent"
                 joinField="operation"/>

        <hasMany name="operationTechnologiesDto" model="operationTechnologyDto"
                 joinField="operation"/>

        <hasMany name="productInComponents" model="productComponent"
                 joinField="operationIn" cascade="delete" copyable="true"/>
        <hasMany name="productOutComponents" model="productComponent"
                 joinField="operationOut" cascade="delete" copyable="true"/>

        <belongsTo name="workstation" plugin="basic" model="workstation" persistent="false"/>
        <manyToMany name="workstations" plugin="basic" model="workstation"
                    joinField="operations" copyable="true"/>

        <enum name="assignedToOperation" values="01workstations,02workstationTypes"
              default="01workstations" required="true"/>

        <boolean name="createOperationOutput" default="false" copyable="false"/>
        <belongsTo name="product" plugin="basic" model="product" copyable="false"/>
        <belongsTo name="workstationType" plugin="basic" model="workstationType"/>
        <belongsTo name="division" plugin="basic" model="division"/>

        <integer name="quantityOfWorkstations" default="1" required="true">
            <validatesRange from="1"/>
        </integer>

        <hasMany name="operationSkills" model="operationSkill" joinField="operation" cascade="delete" copyable="false"/>
        <hasMany name="technologicalProcessLists" model="technologicalProcessList" joinField="operation"/>

        <boolean name="showInProductData" default="false"/>
        <boolean name="reservationRawMaterialResourceRequired" default="false"/>
        <decimal name="productDataNumber" default="0"/>

        <hasMany name="dashboardOperations" joinField="dashboardOperation"
                       plugin="basic" model="parameter" cascade="nullify"/>
    </fields>

    <hooks>
        <validatesWith class="com.qcadoo.mes.technologies.hooks.OperationModelValidators"
                       method="checkIfProductsInProductComponentsAreDistinct"/>


        <onSave class="com.qcadoo.mes.technologies.hooks.OperationModelHooks" method="onSave"/>
    </hooks>

    <identifier expression="#number + ' - ' + #name"/>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-cmms-machine-parts/src/main/resources/cmmsMachineParts/model/plannedEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="plannedEvent" auditable="true" versionable="true"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <string name="number" required="true" unique="true"/>
        <enum name="type"
              values="01review,02repairs,03externalService,04udtReview,05meterReading,06manual,07additionalWork,08afterReview"
              default="01review" required="true"/>
        <string name="description">
            <validatesLength max="600"/>
        </string>
        <belongsTo name="owner" model="staff" plugin="basic"/>
        <!-- only for show in grid-->
        <string name="ownerName"/>

        <enum name="state"
              values="01new,02inPlan,03planned,04inRealization,05realized,06canceled,07accepted,08inEditing" default="01new"/>

        <belongsTo name="factory" model="factory" plugin="basic" required="true"/>
        <belongsTo name="division" model="division" plugin="basic" required="true"/>
        <belongsTo name="productionLine" model="productionLine" plugin="productionLines"/>
        <belongsTo name="workstation" model="workstation" plugin="basic"/>
        <belongsTo name="subassembly" model="subassembly" plugin="basic"/>
        <belongsTo name="company" model="company" plugin="basic"/>
        <belongsTo name="sourceCost" model="sourceCost"/>

        <boolean name="plannedSeparately" default="false"/>
        <boolean name="requiresShutdown" default="false"/>
        <boolean name="acceptanceEvents" default="false" persistent="false"/>


        <enum name="basedOn" values="01date,02counter" default="01date" required="true"/>
        <date name="date"/>

        <decimal name="counter">
            <validatesRange from="0" exclusively="false"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>
        <decimal name="counterTolerance">
            <validatesRange from="0" exclusively="false"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>

        <integer name="duration" default="0"/>
        <integer name="effectiveDuration" default="0"/>

        <decimal name="effectiveCounter">
            <validatesRange from="0" exclusively="false"/>
            <validatesUnscaledValue max="9"/>
            <validatesScale max="5"/>
        </decimal>

        <datetime name="startDate"/>
        <datetime name="finishDate"/>
        <boolean name="isDeadline"/>
        <manyToMany name="responsibleWorkers" joinField="plannedEvents" model="staff" cascade="nullify" plugin="basic"
                    copyable="false"/>

        <hasMany name="realizations" model="plannedEventRealization" joinField="plannedEvent" copyable="false"
                 cascade="delete"/>

        <belongsTo name="plannedEventContext" plugin="cmmsMachineParts" model="plannedEventContext"/>

        <hasMany name="actions" model="actionForPlannedEvent" joinField="plannedEvent" cascade="delete"
                 copyable="true"/>

        <text name="solutionDescription"/>
        <hasMany name="machinePartsForEvent" model="machinePartForEvent" joinField="plannedEvent" cascade="delete"
                 copyable="true"/>

        <hasMany name="attachments" model="plannedEventAttachment" joinField="plannedEvent" cascade="delete"/>

        <hasMany name="documents" model="document" plugin="materialFlowResources" joinField="plannedEvent"
                 copyable="false"
                 cascade="nullify"/>

        <manyToMany name="relatedEvents" joinField="relatedEvents" columnName="relatedEvent" model="plannedEvent"
                    cascade="nullify"
                    copyable="false"/>

        <hasMany name="stateChanges" joinField="plannedEvent" model="plannedEventStateChange" cascade="delete"
                 copyable="false"/>

        <boolean name="afterReview" default="false"/>

        <belongsTo name="maintenanceEvent" model="maintenanceEvent" plugin="cmmsMachineParts"/>

    </fields>
    <hooks>
        <validatesWith class="com.qcadoo.mes.cmmsMachineParts.validators.PlannedEventValidators"
                       method="validatesWith"/>
        <onSave class="com.qcadoo.mes.cmmsMachineParts.hooks.PlannedEventHooks" method="onSave"/>
        <onCreate class="com.qcadoo.mes.cmmsMachineParts.hooks.PlannedEventHooks" method="onCreate"/>
        <onCopy class="com.qcadoo.mes.cmmsMachineParts.hooks.PlannedEventHooks" method="onCopy"/>
        <onDelete class="com.qcadoo.mes.cmmsMachineParts.hooks.PlannedEventHooks" method="onDelete"/>
    </hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-cmms-machine-parts/src/main/resources/cmmsMachineParts/model/plannedEventContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.4

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="plannedEventContext"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
       xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
    <fields>
        <belongsTo name="factory" model="factory" plugin="basic"/>
        <belongsTo name="division" model="division" plugin="basic"/>
        <hasMany name="plannedEvents" model="plannedEvent"
                 joinField="plannedEventContext" plugin="cmmsMachineParts"/>

        <hasMany name="plannedEventsDtos" model="plannedEventListDto"
                 joinField="plannedEventContext" plugin="cmmsMachineParts"/>

        <boolean name="generated" default="false"/>
        <boolean name="confirmed" default="false"/>
        <boolean name="acceptanceEvents" default="false" persistent="false"/>

    </fields>
    <hooks>

    </hooks>
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-product-catalog-numbers/src/main/resources/productCatalogNumbers/model/productCatalogNumbers.xml
<?xml version="1.0" encoding="UTF-8"?>
<model name="productCatalogNumbers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">
	<fields>
		<string name="catalogNumber" required="true" >
			<validatesLength max="256" />
		</string>
		<belongsTo name="product" model="product" plugin="basic" required="true"/>
		<belongsTo name="company" model="company" plugin="basic" required="true"/>
	</fields>
	<hooks >
		<validatesWith class="com.qcadoo.mes.productCatalogNumbers.hooks.ProductCatalogNumbersHooks" method="checkIfExistsCatalogNumberWithProductAndCompany" />
		<validatesWith class="com.qcadoo.mes.productCatalogNumbers.hooks.ProductCatalogNumbersHooks" method="checkIfExistsCatalogNumberWithNumberAndCompany" />
 	</hooks>
	<identifier expression="#number + ' - ' + #company.get('name')" />
</model>

=== qcadoo/mes/mes-plugins/mes-plugins-work-plans/src/main/resources/workPlans/model/workPlan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    ***************************************************************************
    Copyright (c) 2010 Qcadoo Limited
    Project: Qcadoo MES
    Version: 1.3

    This file is part of Qcadoo.

    Qcadoo is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation; either version 3 of the License,
    or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
    ***************************************************************************

-->
<model name="workPlan" activable="true"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schema.qcadoo.org/model"
	xsi:schemaLocation="http://schema.qcadoo.org/model http://schema.qcadoo.org/model.xsd">

	<fields>
		<string name="name" required="true" unique="true">
			<validatesLength max="1024" />
		</string>
		<datetime name="date" />
		<string name="worker" />
		<boolean name="generated" />
		<string name="fileName" />
		<boolean name="dontPrintOrdersInWorkPlans" />

		<enum name="type"
			values="01noDistinction,02byEndProduct,03byWorkstationType,04byDivision"
			default="01allOperations" required="true" />

		<hasMany name="workPlanOrderColumns" plugin="workPlans"
			model="workPlanOrderColumn" joinField="workPlan" cascade="delete"
			copyable="true" />

		<manyToMany name="orders" joinField="workPlans" model="order"
			plugin="orders" copyable="true" />

		<belongsTo name="inputProductColumnToSortBy" model="columnForInputProducts" />
		<enum name="orderSorting" values="01asc,02desc"/>

	</fields>

	<hooks>
		<onCreate class="com.qcadoo.mes.workPlans.hooks.WorkPlanHooks"
			method="onCreate" />
		<onCopy class="com.qcadoo.mes.workPlans.hooks.WorkPlanHooks"
			method="onCopy" />
	</hooks>

	<identifier expression="#name" />
</model>
